"""add_user_item_fields

Revision ID: 4ce7317cd625
Revises: 5e45f5ec8c27
Create Date: 2025-07-12 11:42:05.614955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce7317cd625'
down_revision: Union[str, Sequence[str], None] = '5e45f5ec8c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('images', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('location', sa.String(), nullable=True))
    op.add_column('items', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('swaps_completed', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('items_listed', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('impact_score', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('join_date', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'join_date')
    op.drop_column('users', 'impact_score')
    op.drop_column('users', 'items_listed')
    op.drop_column('users', 'swaps_completed')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'name')
    op.drop_column('items', 'date_added')
    op.drop_column('items', 'points')
    op.drop_column('items', 'location')
    op.drop_column('items', 'images')
    # ### end Alembic commands ###
